### ISSUE TITLE
Drop Core framwork for OS X

### ISSUE THREAD

**Issue by sago007** [sago007/PlatformFolders#14]
At the moment PlatformFolders uses CoreServices to find the relevant folders on OS X. However that may be overkill.

Unlike other operating system (like Linux and Windows) OS X does not allow the common directories to be moved or renamed. Moving a folder to another drive involves symlinking it and translations are done fully in the UI. 

The "Public" folder is already hardcoded as it is not supported by FSFindFolder. I wonder if I should do the same with the rest. Can anyone see anything bad in this approach?

Reference:
https://apple.stackexchange.com/questions/145476/move-documents-folder-to-different-drive
https://developer.apple.com/library/archive/documentation/General/Conceptual/MOSXAppProgrammingGuide/AppRuntime/AppRuntime.html
https://apple.stackexchange.com/questions/24159/how-do-i-rename-the-downloads-folder-in-lion/24258#24258

**Comment by sum01** [comment]
I don't know much about macOS, but if they made the folders unmoveable then I guess hardcoding paths isn't terrible. Especially since those FSXXX calls are deprecated.

**Comment by sago007** [comment]
Looking a bit further. There might be a way to call the new API. While all Apple documentation refers to the Objective-C way, the underlying C interface is apparently exposed: http://opensource.apple.com//source/Libc/Libc-825.40.1/include/NSSystemDirectories.h
This seems to be the right way.

**Comment by sum01** [comment]
But is that header actually part of any public API, or is it subject to be changed on a whim by Apple?

**Comment by sago007** [comment]
Reading the source code http://opensource.apple.com//source/Libc/Libc-825.40.1/gen/NSSystemDirectories.c
it turned out that all values are hard coded. The function also contains "~" in the result and expanding is left as an exercise to the reader. So it makes sense to just do like "Public" for all Mac folders.

**Comment by sago007** [comment]
All paths for Mac are now hard coded.
