### ISSUE TITLE
Consider header-only library?

### ISSUE THREAD

**Issue by space55** [sago007/PlatformFolders#22]
Hello,

I found this library at a perfect moment - just when I started having bugs on Apple devices due to platform-specific folders. I'm enjoying it so far, but had one question about it: are there any plans to convert it to a header-only library, that way I don't have to mark the .cpp file as a source?

Thanks!

**Comment by sago007** [comment]
I considered it. I decided against it due to different platforms having different include requirements and I would quickly expose something I should not.
