### ISSUE TITLE
Add Linux XDG State directory

### ISSUE THREAD

**Issue by Athonathonathon** [sago007/PlatformFolders#25]
Recently (not sure exactly when, but it's in version 0.8 of the spec), the XDG Base Directory specification added a new directory for state information such as log files and session data. This can be used as a replacement for game save directories mentioned [here](https://github.com/sago007/PlatformFolders/blob/0d31bd285ff41a7f78ea5e2b9f081b39a4af26f6/sago/platform_folders.h#L255).

As per the [specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html):
>  The $XDG_STATE_HOME contains state data that should persist between (application) restarts, but that is not important or portable enough to the user that it should be stored in $XDG_DATA_HOME. It may contain:
> 
>  - actions history (logs, history, recently used files, …)
>
>  - current state of the application that can be reused on a restart (view, layout, open files, undo history, …)

**Comment by sago007** [comment]
I did see it. I believe it maps recently well to LOCALAPPDATA on Windows.

I am not sure about using it for games. It says "not important or portable enough to the user" and save games are currently one of the most important things in ".local/share".

Looking at my current ".local/share" there are certainly a lot of things that could go into "./local/state" instead.
I do want to add the state folder. As mentioned it matches LOCALAPPDATA on Windows very well. It does not have an equivalent on Mac OS X but Application Support should handle it.

**Comment by sago007** [comment]
The state dir is now exposed in version 4.2.0 as "sago::getStateDir()"
